-- =============================================================================
-- VERIFICAÇÃO (somente leitura): funções public esperadas em database.types.ts
-- GERADO POR: node scripts/generate-verify-sql-from-types.mjs
-- NÃO EDITAR À MÃO — regenere após atualizar database.types.ts
-- Total: 157 nomes
-- Executar: Supabase → SQL Editor
-- =============================================================================

WITH expected(name) AS (
  VALUES
    ('_provisionar_rpcs_escrita_a'),
    ('_provisionar_rpcs_escrita_b'),
    ('_provisionar_rpcs_leitura'),
    ('_provisionar_tabelas'),
    ('admin_criar_cupom'),
    ('admin_excluir_cupom'),
    ('admin_listar_cupons'),
    ('create_tenant_schema'),
    ('criar_rpcs_tenant'),
    ('debug_check_tabela_registros'),
    ('debug_columns_test'),
    ('debug_financeiro_check'),
    ('debug_get_create_produto_args'),
    ('debug_get_os_signature'),
    ('debug_get_source'),
    ('debug_kpis_source'),
    ('debug_listar_clientes'),
    ('debug_listar_signature'),
    ('debug_listar_signatures'),
    ('deletar_empresa_master'),
    ('drop_old_tenant_atualizar_cliente'),
    ('drop_old_tenant_criar_cliente'),
    ('execute_dynamic_ddl'),
    ('get_clientes_tenant'),
    ('get_current_empresa_id'),
    ('get_current_role'),
    ('get_estoque_baixo'),
    ('get_pendencias_financeiro'),
    ('get_tabela_tenant'),
    ('get_tenant_schema'),
    ('get_user_settings'),
    ('get_vendas_periodo'),
    ('incrementar_numero_nfe'),
    ('incrementar_uso_cupom'),
    ('insert_tabela_tenant'),
    ('is_master'),
    ('is_tenant_of'),
    ('listar_modulos_avulsos_checkout'),
    ('listar_planos_checkout'),
    ('master_atualizar_modulo_avulso'),
    ('master_atualizar_plano'),
    ('master_listar_historico_precos'),
    ('mestre_prorrogar_trial_empresa'),
    ('obter_schema_usuario'),
    ('provision_base_tables'),
    ('provisionar_empresa'),
    ('provisionar_empresa_master'),
    ('provisionar_novo_tenant'),
    ('registrar_audit'),
    ('relatorio_estoque_tenant'),
    ('relatorio_financeiro_tenant'),
    ('relatorio_vendas_tenant'),
    ('set_tenant_schema'),
    ('tenant_abrir_ordem_producao'),
    ('tenant_adicionar_tag'),
    ('tenant_atualizar_cliente'),
    ('tenant_atualizar_comissao'),
    ('tenant_atualizar_custo_produto'),
    ('tenant_atualizar_dados_pessoais'),
    ('tenant_atualizar_demanda_real'),
    ('tenant_atualizar_estoque'),
    ('tenant_atualizar_financeiro'),
    ('tenant_atualizar_funcionario'),
    ('tenant_atualizar_modulos_usuario'),
    ('tenant_atualizar_obra'),
    ('tenant_atualizar_os'),
    ('tenant_atualizar_produto'),
    ('tenant_atualizar_produto_fiscal'),
    ('tenant_buscar_configuracao'),
    ('tenant_buscar_produto_por_codigo'),
    ('tenant_calcular_valor_estoque'),
    ('tenant_cancelar_transferencia'),
    ('tenant_concluir_ordem_producao'),
    ('tenant_concluir_transferencia'),
    ('tenant_criar_alerta_nurturing'),
    ('tenant_criar_cliente'),
    ('tenant_criar_ficha_tecnica'),
    ('tenant_criar_financeiro'),
    ('tenant_criar_funcionario'),
    ('tenant_criar_interacao'),
    ('tenant_criar_kit'),
    ('tenant_criar_local_estoque'),
    ('tenant_criar_obra'),
    ('tenant_criar_os'),
    ('tenant_criar_produto'),
    ('tenant_criar_regra_comissao'),
    ('tenant_criar_transferencia'),
    ('tenant_dashboard_kpis'),
    ('tenant_dashboard_kpis_por_mes'),
    ('tenant_dashboard_metricas'),
    ('tenant_desativar_local_estoque'),
    ('tenant_enviar_campanha'),
    ('tenant_excluir_cliente'),
    ('tenant_excluir_documento'),
    ('tenant_excluir_financeiro'),
    ('tenant_excluir_funcionario'),
    ('tenant_excluir_interacao'),
    ('tenant_excluir_kit'),
    ('tenant_excluir_obra'),
    ('tenant_excluir_os'),
    ('tenant_excluir_produto'),
    ('tenant_excluir_regra_comissao'),
    ('tenant_excluir_venda'),
    ('tenant_finalizar_alerta_nurturing'),
    ('tenant_gerar_codigo_barras'),
    ('tenant_gerar_previsao_demanda'),
    ('tenant_gerenciar_timer_os'),
    ('tenant_importar_clientes_lote'),
    ('tenant_listar_alertas_estoque'),
    ('tenant_listar_audit'),
    ('tenant_listar_clientes'),
    ('tenant_listar_comissoes'),
    ('tenant_listar_documentos'),
    ('tenant_listar_equipes'),
    ('tenant_listar_estoque'),
    ('tenant_listar_fichas_tecnicas'),
    ('tenant_listar_financeiro'),
    ('tenant_listar_funcionarios'),
    ('tenant_listar_interacoes'),
    ('tenant_listar_kits'),
    ('tenant_listar_locais_estoque'),
    ('tenant_listar_modulos_usuario'),
    ('tenant_listar_movimentacao_estoque'),
    ('tenant_listar_obras'),
    ('tenant_listar_ordens_producao'),
    ('tenant_listar_ordens_servico'),
    ('tenant_listar_previsoes_demanda'),
    ('tenant_listar_produtos'),
    ('tenant_listar_produtos_fiscal'),
    ('tenant_listar_regras_comissao'),
    ('tenant_listar_tags_catalog'),
    ('tenant_listar_transferencias'),
    ('tenant_listar_usuarios'),
    ('tenant_listar_vendas'),
    ('tenant_marcar_fechamento_visto'),
    ('tenant_obter_documento'),
    ('tenant_obter_dre'),
    ('tenant_obter_fechamento_pendente'),
    ('tenant_obter_lucro_os'),
    ('tenant_obter_sugestoes_nurturing'),
    ('tenant_processar_venda'),
    ('tenant_registrar_documento'),
    ('tenant_registrar_pagamento_rh'),
    ('tenant_registrar_pagamento_rh_todos'),
    ('tenant_remover_tag'),
    ('tenant_resolver_alerta_estoque'),
    ('tenant_salvar_configuracao'),
    ('tenant_vender_kit'),
    ('tenant_verificar_alertas_estoque'),
    ('update_all_tenants_atualizar_cliente'),
    ('update_all_tenants_criar_cliente'),
    ('update_clientes_funil_fase_constraint'),
    ('update_user_settings'),
    ('upgrade_all_tenants'),
    ('validar_cupom'),
    ('verificar_limite_usuarios'),
    ('webhook_provisionar_assinatura')
),
live AS (
  SELECT DISTINCT p.proname AS name
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND p.prokind IN ('f', 'p')
)
SELECT
  e.name AS expected_function,
  EXISTS (SELECT 1 FROM live l WHERE l.name = e.name) AS present_in_db
FROM expected e
ORDER BY e.name;

-- Opcional: funções em public que NÃO estão no types (drift reverso)
-- SELECT l.name
-- FROM live l
-- WHERE NOT EXISTS (SELECT 1 FROM expected e WHERE e.name = l.name)
-- ORDER BY 1;
