 CREATE OR REPLACE FUNCTION public.tenant_listar_clientes(p_cursor uuid DEFAULT NULL::uuid, p_limit integer DEFAULT 20, p_status text DEFAULT NULL::text, p_funil_fase text DEFAULT NULL::text, p_busca text DEFAULT NULL::text, p_order_by text DEFAULT 'criado_em'::text, p_order_dir text DEFAULT 'DESC'::text, p_tags text[] DEFAULT NULL::text[])+
  RETURNS SETOF jsonb                                                                                                                                                                                                                                                                                                                                 +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                    +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                    +
 AS $function$                                                                                                                                                                                                                                                                                                                                        +
 DECLARE                                                                                                                                                                                                                                                                                                                                              +
   v_tenant_schema TEXT;                                                                                                                                                                                                                                                                                                                              +
   v_result JSONB;                                                                                                                                                                                                                                                                                                                                    +
 BEGIN                                                                                                                                                                                                                                                                                                                                                +
   -- Obter schema do tenant                                                                                                                                                                                                                                                                                                                          +
   SELECT e.schema_name INTO v_tenant_schema                                                                                                                                                                                                                                                                                                          +
   FROM public.user_profiles up                                                                                                                                                                                                                                                                                                                       +
   JOIN public.empresas e ON e.id = up.empresa_id                                                                                                                                                                                                                                                                                                     +
   WHERE up.user_id = auth.uid();                                                                                                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                                                                                                                                      +
   IF v_tenant_schema IS NULL THEN                                                                                                                                                                                                                                                                                                                    +
     RETURN QUERY SELECT '[]'::jsonb;                                                                                                                                                                                                                                                                                                                 +
     RETURN;                                                                                                                                                                                                                                                                                                                                          +
   END IF;                                                                                                                                                                                                                                                                                                                                            +
                                                                                                                                                                                                                                                                                                                                                      +
   -- Executar RPC no schema do tenant e converter para JSONB                                                                                                                                                                                                                                                                                         +
   FOR v_result IN EXECUTE format('                                                                                                                                                                                                                                                                                                                   +
     SELECT jsonb_agg(                                                                                                                                                                                                                                                                                                                                +
       jsonb_build_object(                                                                                                                                                                                                                                                                                                                            +
         ''id'', c.id,                                                                                                                                                                                                                                                                                                                                +
         ''nome'', c.nome,                                                                                                                                                                                                                                                                                                                            +
         ''email'', c.email,                                                                                                                                                                                                                                                                                                                          +
         ''telefone'', c.telefone,                                                                                                                                                                                                                                                                                                                    +
         ''funil_fase'', c.funil_fase,                                                                                                                                                                                                                                                                                                                +
         ''status'', c.status,                                                                                                                                                                                                                                                                                                                        +
         ''tags'', c.tags,                                                                                                                                                                                                                                                                                                                            +
         ''criado_em'', c.criado_em,                                                                                                                                                                                                                                                                                                                  +
         ''atualizado_em'', c.atualizado_em,                                                                                                                                                                                                                                                                                                          +
         ''next_cursor'', c.next_cursor                                                                                                                                                                                                                                                                                                               +
       )                                                                                                                                                                                                                                                                                                                                              +
     )                                                                                                                                                                                                                                                                                                                                                +
     FROM %I.tenant_listar_clientes($1, $2, $3, $4, $5, $6, $7, $8)                                                                                                                                                                                                                                                                                   +
   ', v_tenant_schema)                                                                                                                                                                                                                                                                                                                                +
   USING p_cursor, p_limit, p_status, p_funil_fase, p_busca, p_order_by, p_order_dir, p_tags                                                                                                                                                                                                                                                          +
   LOOP                                                                                                                                                                                                                                                                                                                                               +
     RETURN NEXT v_result;                                                                                                                                                                                                                                                                                                                            +
   END LOOP;                                                                                                                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                                                                                                                                      +
 EXCEPTION WHEN OTHERS THEN                                                                                                                                                                                                                                                                                                                           +
   -- Em caso de erro, retornar array vazio                                                                                                                                                                                                                                                                                                           +
   RETURN QUERY SELECT '[]'::jsonb;                                                                                                                                                                                                                                                                                                                   +
 END;                                                                                                                                                                                                                                                                                                                                                 +
 $function$                                                                                                                                                                                                                                                                                                                                           +
 

